Skill tooltips
AoTTG-2/Aottg2-Unity pull request #115
Opened 2024-09-15 13:46 UTC by mwnDK1402

Repeat of all the commit messages:

> HoverTooltip shows and hides the popup when the mouse enters and exits a graphic.
Can be added seamlessly through code, or in the editor.
HoverTooltips added through code can be customized by adding in the editor instead and modifying the default values of the properties, assuming the code doesn't set them.
This is accomplished through GetOrAddComponent. Make sure to use it.
No tooltips are shown if the tooltip is empty.
Changing the tooltip colors by adding fields to the JSON themes avoids breaking any themes.

### Todo

- [x] Show a tooltip when hovering over skills
- [x] Allow the tooltip theme to change independently of other tooltips
- [ ] Write skill tooltips
- [ ] Determine skill tooltip colors for dark and light themes

2024-09-15 22:41 UTC, mwnDK1402 commented
The themes can be modified at any time, so I'd say this is ready to review.

2024-09-17 00:56 UTC, rc174945 requested changes

2024-09-17 00:56 UTC, rc174945 commented on Assets/Scripts/Characters/Human/HumanSpecials.cs
> +            HashSet<string> names = new HashSet<string>();
Do we lose the skill order display by using hashet? We want to preserve order as it's defined in AnySpecials followed by the other groups

2024-09-17 00:56 UTC, rc174945 commented on Assets/Scripts/UI/InGameMenu/CharacterHumanPanel.cs
> +            var skillPopup = ElementFactory.CreateTooltipPopup<SkillTooltipPopup>(UIManager.CurrentMenu.IconPickPopup.transform).GetComponent<TooltipPopup>();
creating popup here will cause a mem leak, because this panel is destroyed/created every time we select the Human category. You should create a menu field like menu.TooltipPopup but for skill tooltip.

2024-09-17 03:24 UTC, mwnDK1402 commented on Assets/Scripts/Characters/Human/HumanSpecials.cs
> +            HashSet<string> names = new HashSet<string>();
I haven't tested this, but I'm almost certain you're right. I'll accept looking through the list sequentially with great sorrow in my heart.

2024-09-17 03:27 UTC, mwnDK1402 commented on Assets/Scripts/UI/InGameMenu/CharacterHumanPanel.cs
> +            var skillPopup = ElementFactory.CreateTooltipPopup<SkillTooltipPopup>(UIManager.CurrentMenu.IconPickPopup.transform).GetComponent<TooltipPopup>();
If the panel is destroyed/created every time we select the Human category, how would that be a memory leak?
In reality, the Tooltip is created when you enter InGameMenu, and it is destroyed when the scene is reloaded, which is when the game restart. Tested this in singleplayer by pressing 'T' to commit die. Deleted the Tooltip that I had renamed and created a new one. There is never a moment when two `SkillTooltipPopup`s exist at the same time.

Regardless, if you don't think this is the correct place to create it, I will look for a better place.

2024-09-17 03:31 UTC, mwnDK1402 commented on Assets/Scripts/Characters/Human/HumanSpecials.cs
> +            HashSet<string> names = new HashSet<string>();
So, interestingly enough, it doesn't make an actual difference when running the game. But I agree that depending on an implementation detail of `HashSet` is incorrect.

2024-09-17 03:32 UTC, rc174945 commented on Assets/Scripts/UI/InGameMenu/CharacterHumanPanel.cs
> +            var skillPopup = ElementFactory.CreateTooltipPopup<SkillTooltipPopup>(UIManager.CurrentMenu.IconPickPopup.transform).GetComponent<TooltipPopup>();
it can happen if you switch between the Human and Titan panels

2024-09-17 03:36 UTC, rc174945 commented on Assets/Scripts/Characters/Human/HumanSpecials.cs
> +            HashSet<string> names = new HashSet<string>();
You dont have to revert this if you don't feel like it then. I guess c# default implementation is ordered.

2024-09-17 03:36 UTC, rc174945 commented on Assets/Scripts/UI/InGameMenu/CharacterHumanPanel.cs
> +            var skillPopup = ElementFactory.CreateTooltipPopup<SkillTooltipPopup>(UIManager.CurrentMenu.IconPickPopup.transform).GetComponent<TooltipPopup>();
because the parent is the main menu, but the panel is calling setup repeatedly if you switch between the Human and Titan tabs.

2024-09-17 04:52 UTC, mwnDK1402 commented on Assets/Scripts/UI/InGameMenu/CharacterHumanPanel.cs
> +            var skillPopup = ElementFactory.CreateTooltipPopup<SkillTooltipPopup>(UIManager.CurrentMenu.IconPickPopup.transform).GetComponent<TooltipPopup>();
You're completely right. I moved the popup into `InGameMenu`, and it solves the issue you pointed out.

2024-09-17 07:24 UTC, rc174945 approved these changes

2024-09-17 07:24 UTC, merged