Better RockThrow
AoTTG-2/Aottg2-Unity pull request #143
Opened 2024-09-26 11:01 UTC by Picadi0

The Titan body will rotate where you look while you are throwing rock and throwing the last position you look.
![Better RockThrow](https://github.com/user-attachments/assets/0ebbb41b-dfcf-4481-9cca-526d50c839a8)

2024-09-26 16:28 UTC, Jestrovich commented
GOD BLESS AOTTG2 DEVS!!!

2024-09-27 02:20 UTC, AutumnThyme commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +            if (!base.AI && base.State == TitanState.Attack && base._currentAttackAnimation == this.BasicAnimations.AttackRockThrow)//kirit00
Remove comment

2024-09-27 02:21 UTC, AutumnThyme commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +                base.Cache.Transform.rotation = Quaternion.Lerp(base.Cache.Transform.rotation, Quaternion.LookRotation(normalized), Time.deltaTime * 25f);
Is there a reason to reference the base classes' cache instead of the Basic Cache?

2024-09-27 02:23 UTC, AutumnThyme commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +                    var body = BasicCache.Core.Find("Controller.Body");
Please Cache all body parts that need to be referenced.
Avoid Find calls as they are expensive.

2024-09-27 02:23 UTC, AutumnThyme requested changes
Please fix issues brought up in the comments

2024-09-27 02:36 UTC, Picadi0 commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +                base.Cache.Transform.rotation = Quaternion.Lerp(base.Cache.Transform.rotation, Quaternion.LookRotation(normalized), Time.deltaTime * 25f);
I wasn't know there was a basic cache I'm new at project now changed it

2024-09-27 02:57 UTC, Picadi0 commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +                    var body = BasicCache.Core.Find("Controller.Body");
it wasn't belong me it's look like changed because of formatter but i cached the body part and used it.

2024-09-27 03:29 UTC, Picadi0 commented
@AutumnThyme Done, if I missunderstand issues and not fixed at all please let me now

2024-09-28 15:08 UTC, closed without merging