grabbed human position fix
AoTTG-2/Aottg2-Unity pull request #145
Opened 2024-09-27 01:48 UTC by Picadi0

When a human is grabbed by a titan, human position wasn't being updated locally, it was being updated remotely, which caused it to look like this
![before](https://github.com/user-attachments/assets/12e2597a-31ef-4050-954c-63dc7805953d)
So Here is the fixed version.
![after](https://github.com/user-attachments/assets/26be5a37-fce7-44a2-b0c9-907493aae135)

2024-09-27 02:24 UTC, AutumnThyme commented on Assets/Scripts/Characters/Human/Human.cs
> +using UnityEngine.XR;
Is this being used?

2024-09-27 02:27 UTC, AutumnThyme commented on Assets/Scripts/Characters/Human/Human.cs
> +                if (grabber.GetCurrentAnimation().Contains("grab") && grabber.GetCurrentAnimation().Contains(".l"))
Not crazy about this pattern for checking grabs/direction, maybe create a function for telling what the type of move is and the direction, multiple Contains calls are a bit messy as well but its a short string so as long as it isn't called a lot its fine.

2024-09-27 02:30 UTC, AutumnThyme requested changes
Remove XR import if not used and create a function for categorizing grabs instead of copying code.
Something like GetGrabHand(animation)

2024-09-27 03:02 UTC, Picadi0 commented on Assets/Scripts/Characters/Human/Human.cs
> +using UnityEngine.XR;
No it's not used and removed all unused libraries

2024-09-27 03:37 UTC, Picadi0 commented on Assets/Scripts/Characters/Human/Human.cs
> +                if (grabber.GetCurrentAnimation().Contains("grab") && grabber.GetCurrentAnimation().Contains(".l"))
LOL yea it's looks funny but was working anyway changed it as you wanted

2024-09-27 03:38 UTC, Picadi0 commented
@AutumnThyme Done

2024-09-28 06:01 UTC, AutumnThyme approved these changes

2024-09-28 06:05 UTC, AutumnThyme approved these changes

2024-09-28 07:53 UTC, merged