CL trigger special & modify cooldown
AoTTG-2/Aottg2-Unity pull request #151
Opened 2024-09-29 05:16 UTC by oryxoik

- Specials can be triggered with `Human.ActivateSpecial()`. It won't be the same as using the special button (because some of them require holding the button) but having this will be useful in some cases like force activating shifter specials
- New `Human.Cooldown` (get, set),  `Human.ShifterLiveTime` (get, set), and `Human.CooldownRatio` (get)
- Character null check in Endless logic

2024-10-01 07:20 UTC, rc174945 commented on Assets/Scripts/CustomLogic/Builtin/CustomLogicHumanBuiltin.cs
> +                return Human.Special == null ? 0f : Human.Special.Cooldown;
Let's rename this to SpecialCooldown

2024-10-01 07:20 UTC, rc174945 commented on Assets/Scripts/CustomLogic/Builtin/CustomLogicHumanBuiltin.cs
> +            if (name == "CooldownRatio")
same here

2024-10-01 07:20 UTC, rc174945 commented on Assets/Scripts/Controllers/BaseTitanAIController.cs
>                      continue;
let's separate this into two cases: if isMapTargetable check the attackInfo.MapObject field, else use the old human logic.

2024-10-01 07:22 UTC, rc174945 commented on Assets/Scripts/Controllers/BaseTitanAIController.cs
>                      continue;
since currently this will skip adding non-HumanOnly attacks to a maptargetable even if MapObject is true

2024-10-02 15:36 UTC, oryxoik commented on Assets/Scripts/Controllers/BaseTitanAIController.cs
>                      continue;
```csharp
                if (isMapTargetable)
                {
                    if (!attackInfo.MapObject)
                        continue;
                }
                else if (attackInfo.HumanOnly && !isHuman)
                    continue;
```
like this?

2024-10-07 07:38 UTC, rc174945 requested changes

2024-10-07 07:38 UTC, rc174945 commented on Assets/Resources/Data/Info/MapPrefabList.json
>  		]
is there a component named AITarget? Did you mean TitanTarget?

2024-10-07 07:38 UTC, rc174945 commented on Assets/Resources/Data/Modes/EndlessLogic.txt
>          }
We should still show how many titans are on the map. Maybe like Titans: 10 instead of Titans Left

2024-10-10 06:11 UTC, rc174945 approved these changes

2024-10-10 06:11 UTC, merged