Physically becoming the garbage collector to improve performance
AoTTG-2/Aottg2-Unity pull request #154
Opened 2024-09-30 04:13 UTC by AutumnThyme

Removed a bunch of allocating calls, fixed some calls that were doing unneeded stuff on Update/FixedUpdate which was degrading performance.

Top Left Hud will need to be redesigned as an actual UI element since thats currently the biggest performance drain from the scripts. Ignoring that, the game for me is officially gpu bound meaning I can't optimize the fps much more than that. There are probably some things in multiplayer that may need looking into since I didn't test too much there and I will do another optimization run probably in another month which will include that.

Frame time for me is 1.5ms - 2ms with spikes to 3ms on weird occasions that might be due to the profiler.
Garbage collection is down to about 3kb/frame which I think is probably reasonable for our case.
FPS stays consistently above 500 fps on 15 titans survival compared to before where it would drop under every few seconds.

Some of the optimizations I did use statics/private object caches for specific cases that stuck out.
Some photon rpcs if sent every frame like titan animation alloc about 1.5kb per request if you don't reuse an object[] for the sent information.

Realistically going forward, for one-off things allocs are fine to use if the code is faster to write.
Anything in update/fixedupdate should be watched for lazy/unneeded alloc calls.

String methods that alloc like Trim or Regex calls should also be avoided every frame if possible.

2024-10-01 07:32 UTC, rc174945 commented on Assets/Scripts/ApplicationManagers/VoiceChatManager.cs
> +                return Microphone.devices.Append(UIManager.GetLocale("Common", "None")).ToArray<string>();
is it a good idea to append to the internal list itself? Wont this cause it to endlessly populate None?

2024-10-01 07:45 UTC, rc174945 commented on Assets/Scripts/Characters/BaseCharacter.cs
>              if (CustomLogicManager.Evaluator != null)
you may want to yield 1 more frame after the while loop so Main and component Inits have a chance to run.

2024-10-01 07:47 UTC, rc174945 commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +                BasicCache.ForearmL.localScale = Vector3.zero;
is there a motivation to use zero vector? I think doing this caused some issues before.

2024-10-01 07:56 UTC, rc174945 commented on Assets/Scripts/Characters/BaseCharacter.cs
> +        private LayerMask GroundMaskLayers = PhysicsLayer.GetMask(PhysicsLayer.TitanMovebox, PhysicsLayer.MapObjectEntities,
did you handle cases where the character overrides GroundMask because they have different layers? (ie. human)

2024-10-02 00:54 UTC, AutumnThyme commented on Assets/Scripts/ApplicationManagers/VoiceChatManager.cs
> +                return Microphone.devices.Append(UIManager.GetLocale("Common", "None")).ToArray<string>();
This is a Linq call, whenever we get the device list, it is making a new list including None. We have to have a refreshed version of the list whenever we get it since the device list can change. As long as we only do this in the menu, this will not affect the game's performance.

2024-10-02 01:00 UTC, AutumnThyme commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +                BasicCache.ForearmL.localScale = Vector3.zero;
I can just create a local copy of this small vector, basically most new calls should be avoided in update calls.

2024-10-02 01:00 UTC, AutumnThyme commented on Assets/Scripts/Characters/BaseCharacter.cs
>              if (CustomLogicManager.Evaluator != null)
Added

2024-10-02 01:03 UTC, AutumnThyme commented on Assets/Scripts/Characters/BaseCharacter.cs
> +        private LayerMask GroundMaskLayers = PhysicsLayer.GetMask(PhysicsLayer.TitanMovebox, PhysicsLayer.MapObjectEntities,
I didn't and this shouldn't affect that at all since its a function. While GetMask allocs, I didn't see the player ground check flagging the editor probably since there was only 1 human ground check compared to 20 titan ground checks. I will replace it just bc I'm already looking at it but it wasn't needed.

2024-10-02 01:25 UTC, AutumnThyme commented
Found an issue with one change, wait on review for a sec

2024-10-15 10:08 UTC, rc174945 requested changes

2024-10-15 10:08 UTC, rc174945 commented on Assets/Scripts/Settings/MultiplayerSettings.cs
>          }
bruh

2024-10-15 10:08 UTC, rc174945 commented on Assets/Scripts/Settings/UISettings.cs
>          public BoolSetting ShowPing = new BoolSetting(false);
can we remove ShowKDR then?

2024-10-16 01:12 UTC, AutumnThyme commented on Assets/Resources/UI/Prefabs/InGame/CharacterInfoPopup.prefab
The popup was modified so that I can give the name a background color when highly visible names are toggled on

2024-10-16 01:13 UTC, AutumnThyme commented on Assets/Resources/UI/Prefabs/InGame/CharacterInfoPopup.prefab
I didn't touch or mean to touch the feed panel

2024-10-16 01:14 UTC, AutumnThyme commented on Assets/Scripts/Settings/MultiplayerSettings.cs
>          }
Sorry, can we move this whole part into the gitignored file so that this doesn't happen?

2024-10-16 01:14 UTC, AutumnThyme commented on Assets/Scripts/Settings/UISettings.cs
>          public BoolSetting ShowPing = new BoolSetting(false);
Yes, will remove it.

2024-10-16 01:20 UTC, AutumnThyme commented on Assets/Resources/Projectiles/Prefabs/Thunderspear.prefab
Thunderspear was modified on purpose, the trail effect was smaller than aottg1 and people were complaining about depth visibility.

2024-10-16 01:22 UTC, AutumnThyme commented on Assets/Resources/Projectiles/Prefabs/Thunderspear.prefab
The other modifications are also related to this.

2024-10-18 06:58 UTC, rc174945 approved these changes

2024-10-18 06:59 UTC, merged