Ping property added to the scoreboard for each player.
AoTTG-2/Aottg2-Unity pull request #156
Opened 2024-10-01 19:07 UTC by BavoDevos

Added a new player property to keep track of player their pings to display this on the scoreboard, currently we refresh the ping every 10 seconds as its not necessary to update this frequently.
![image_2024-10-01_210725409](https://github.com/user-attachments/assets/f5b353bc-6821-4879-9cec-a5444b7c56ed)

2024-10-02 06:36 UTC, AutumnThyme commented on Assets/Scripts/GameManagers/InGameManager.cs
> +                timeSinceLastPingUpdate= 0f;
fix space missing here

2024-10-02 06:37 UTC, AutumnThyme commented on Assets/Scripts/CustomLogic/Builtin/CustomLogicPlayerBuiltin.cs
> +                Player.SetCustomProperty(PlayerProperty.Ping, (int)value);
Don't let CL override ping property.

2024-10-02 06:38 UTC, AutumnThyme commented on Assets/Scripts/UI/InGameMenu/ScoreboardScorePanel.cs
> +                //    t.GetComponent<LayoutElement>().preferredWidth = GetPanelWidth() / 3f;
Remove unused code.

2024-10-02 06:38 UTC, AutumnThyme commented on Assets/Scripts/UI/InGameMenu/ScoreboardScorePanel.cs
> +            //    t.GetComponent<LayoutElement>().preferredWidth = GetPanelWidth() / 3f;
Remove unused code.

2024-10-02 06:38 UTC, AutumnThyme commented on Assets/Scripts/UI/InGameMenu/ScoreboardScorePanel.cs
> +                foreach (string property in new string[] { "Kills", "Deaths", "HighestDamage", "TotalDamage"})
weird spacing

2024-10-02 06:40 UTC, AutumnThyme requested changes
See requested changes

2024-10-03 06:31 UTC, BavoDevos commented
Changes have been made and this pull request should now be ready to be closed, if no other issues popup ofcours!

2024-10-07 07:42 UTC, rc174945 approved these changes

2024-10-07 07:43 UTC, merged