Human throw by Titan
AoTTG-2/Aottg2-Unity pull request #185
Opened 2024-10-30 06:25 UTC by Picadi0

if titan grab human with right hand and if PT press any key before eat the human, the human will be throwed by titan !
This feature is most liked things in custom mods in Aottg 1. For fun why not, let's add this.

![HumanThrow2](https://github.com/user-attachments/assets/061fd9bd-5783-4c78-829d-d089275fe220)
![HumanThrow1](https://github.com/user-attachments/assets/1b132278-83b0-4ecc-90a4-8cb06ca81882)

2024-10-31 02:14 UTC, rc174945 requested changes

2024-10-31 02:14 UTC, rc174945 commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +            if (HoldHuman != null && !HoldHumanLeft && (Input.anyKeyDown || State == TitanState.HumanThrow))
check for nonAI

2024-10-31 02:14 UTC, rc174945 commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +                StateAction(TitanState.HumanThrow, "Amarture_VER2|attack.throw");
use our static animation field instead of magic string

2024-10-31 02:14 UTC, rc174945 commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +                Human temp = HoldHuman;
should check if human is not null and still alive here

2024-10-31 02:39 UTC, Picadi0 commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +                StateAction(TitanState.HumanThrow, "Amarture_VER2|attack.throw");
LOL aight

2024-10-31 03:07 UTC, Picadi0 commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +                Human temp = HoldHuman;
checked on the UpdateEat the function where i called from

2024-10-31 05:04 UTC, Picadi0 commented
ready to merge it

2024-12-08 02:09 UTC, Picadi0 commented on Assets/Scripts/Characters/Titan/BasicTitan.cs
> +            if (HoldHuman != null && !HoldHumanLeft && (Input.anyKeyDown || State == TitanState.HumanThrow))
checked on the UpdateEat the function where i called from

2024-12-21 20:16 UTC, rc174945 approved these changes

2024-12-21 20:16 UTC, merged