Thyme destructibles and velocity zones
AoTTG-2/Aottg2-Unity pull request #48
Opened 2024-01-20 06:57 UTC by AutumnThyme

Destructibles allow for triggers to switch between two map objects.
Velocity Zones (currently only works for players) allow a defined zone in which a player (or eventually map object when triggers work for those) to have a force added to their rigidbody OnTriggerStay. Logic is implemented for MapObjects but as triggers cannot detect map objects currently, it does nothing.

2024-01-22 09:41 UTC, rc174945 requested changes

2024-01-22 09:41 UTC, rc174945 commented on Assets/Scripts/CustomLogic/Builtin/CustomLogicListBuiltin.cs
> +            if (methodName == "Contains")
Will contains work on builtins or structs (CustomLogicTitanBuiltin, CustomLogicVector3Builtin?) You may need to manually iterate and use '==' operator on each item since we override equals but not hash

2024-01-22 09:41 UTC, rc174945 commented on Assets/Scripts/CustomLogic/Builtin/CustomLogicMapObjectBuiltin.cs
>                      else if (param == "AddForce")
I think we can simplify addforce a little since Unity's inbuilt is a little confusing, and also the "type" parameter makes things verbose. Velocitychange and impulse for example aren't necessary since that's the same as modifying the velocity directly, and force/acceleration are the same except one uses mass. 
We should instead make addforce only accept acceleration input, and expose Mass as a field in rigidbody and characters.

2024-01-22 09:41 UTC, rc174945 commented on Assets/Resources/Data/Modes/BaseLogic.txt
> +            other.UpdateBuiltinComponent("Rigidbody", "AddForce", force, self.ForceMode);
We should avoid using UpdateBuiltinComponent except for on the component class itself (ie Class Rigidbody). Instead you should update the Rigidbody component to have AddForce, then reference GetComponent("Rigidbody") in custom logic and then call AddForce on it (ie _rigidBody.AddForce())

2024-01-22 22:02 UTC, AutumnThyme commented on Assets/Resources/Data/Modes/BaseLogic.txt
> +            other.UpdateBuiltinComponent("Rigidbody", "AddForce", force, self.ForceMode);
Is there a reason to avoid this? otherwise I'd prefer to keep it and forcemode (the latter of which isn't really possible if I use the rigidbody component directly since it doesn't support force modes and I don't believe optional args are possible in cl.

2024-01-22 22:02 UTC, AutumnThyme commented on Assets/Scripts/CustomLogic/Builtin/CustomLogicMapObjectBuiltin.cs
>                      else if (param == "AddForce")
Its way easier to just expose the force type as a optional variable than to have people manually do the math to change velocity.

2024-01-22 23:33 UTC, AutumnThyme commented on Assets/Resources/Data/Modes/BaseLogic.txt
> +            other.UpdateBuiltinComponent("Rigidbody", "AddForce", force, self.ForceMode);
Or sorry I guess I can do this by just adding another method to the rigidbody class that takes in the force mode.

2024-01-22 23:44 UTC, AutumnThyme commented on Assets/Scripts/CustomLogic/Builtin/CustomLogicListBuiltin.cs
> +            if (methodName == "Contains")
Changed.

2024-01-22 23:45 UTC, AutumnThyme commented on Assets/Resources/Data/Modes/BaseLogic.txt
> +            other.UpdateBuiltinComponent("Rigidbody", "AddForce", force, self.ForceMode);
Added another method to the rigidbody component for handling forcemode then replaced the update and read component methods with GetComponent("Rigidbody") and used the rigid body methods.

2024-02-03 18:53 UTC, rc174945 approved these changes

2024-02-03 18:55 UTC, merged